[mypy]
packages = prime_backup
exclude_gitignore = True

allow_redefinition = True
check_untyped_defs = True
# https://github.com/python/mypy/issues/4717
disable_error_code = type-abstract


[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-fuse]
ignore_missing_imports = True

[mypy-lz4.*]
ignore_missing_imports = True