import contextlib
import dataclasses
import enum
import logging
import os
import time
from concurrent.futures import Future
from pathlib import Path
from typing import BinaryIO, Dict, List, Optional, Union

from prime_backup.action.helpers.blob_creator_common import BlobLookupRoutine, BlobCreateContext, BlobCreatorBase
from prime_backup.action.helpers.blob_pre_calc_result import BlobPrecalculateResult
from prime_backup.action.helpers.chunk_grouper import ChunkGrouper
from prime_backup.action.helpers.create_backup_utils import CreateBackupTimeCostKey, SourceFileNotFoundWrapper
from prime_backup.compressors import Compressor, CompressMethod
from prime_backup.db import schema
from prime_backup.db.session import DbSession
from prime_backup.db.values import BlobStorageMethod
from prime_backup.types.chunk_method import ChunkMethod
from prime_backup.types.chunker import PrettyChunk, PrettyChunkSequence, SimplePrettyChunkSequence
from prime_backup.types.units import ByteCount
from prime_backup.utils import chunk_utils, file_utils, hash_utils, misc_utils
from prime_backup.utils.thread_pool import FailFastBlockingThreadPool


class _ChunkedBlobCreatePolicy(enum.Enum):
	copy_hash = enum.auto()  # files that keep changing: copy to temp file, calc hash, compress to blob  |  read 2x, write 2x. need more spaces
	default = enum.auto()    # default policy: hash+chunking and check, then chunking+compress+hash to blob store          |  read 2x, write 1x


@dataclasses.dataclass(frozen=True)
class _ChunkedBlobPlan:
	policy: _ChunkedBlobCreatePolicy
	pre_cal_result: Optional[BlobPrecalculateResult]


@dataclasses.dataclass(frozen=True)
class _ChunkedBlobSnapshot:
	chunks: PrettyChunkSequence
	blob_hash: str
	blob_size: int


@dataclasses.dataclass
class _PendingChunk:
	hash: str
	compress: str
	raw_size: int
	stored_size: int
	pack_id: int
	pack_offset: int

	def to_insert_kwargs(self) -> DbSession.CreateChunkKwargs:
		return {
			'hash': self.hash,
			'compress': self.compress,
			'raw_size': self.raw_size,
			'stored_size': self.stored_size,
			'pack_id': self.pack_id,
			'pack_offset': self.pack_offset,
		}

	def to_chunk_like(self, chunk_id: int) -> ChunkGrouper.ChunkLike:
		return ChunkGrouper.ChunkLike(
			id=chunk_id,
			hash=self.hash,
			raw_size=self.raw_size,
			stored_size=self.stored_size,
		)


@dataclasses.dataclass(frozen=True)
class _CompressedChunk:
	chunk: _PendingChunk
	data: bytes


@dataclasses.dataclass
class _CompressedChunkWriteState:
	futures: List[Future[_CompressedChunk]] = dataclasses.field(default_factory=list)
	pending_bytes: int = 0
	max_pending_chunks: int = 10
	max_pending_bytes: int = 32 * 1024 * 1024

	def should_flush(self, force: bool) -> bool:
		if len(self.futures) == 0:
			return False
		return force or len(self.futures) >= self.max_pending_chunks or self.pending_bytes >= self.max_pending_bytes


@dataclasses.dataclass(frozen=True)
class _ChunkWriteResult:
	offset_to_chunk: Dict[int, Union[schema.Chunk, _PendingChunk]]
	new_chunks: List[_PendingChunk]
	raw_size_sum: int
	stored_size_sum: int
	unique_chunk_count: int


class ChunkedBlobCreator(BlobCreatorBase):
	@dataclasses.dataclass(frozen=True)
	class Args:
		src_path: Path
		src_path_md5: str
		st: os.stat_result
		chunk_method: ChunkMethod
		last_chance: bool
		is_mutating_file: bool

	def __init__(self, context: BlobCreateContext, args: Args):
		super().__init__(context)
		self.args = args

	def get_or_create(self) -> BlobLookupRoutine[schema.Blob]:
		src_path_str = repr(self.args.src_path.as_posix())
		plan = self.__select_plan()

		with contextlib.ExitStack() as es:
			actual_path_to_read = self.__prepare_path_to_read(es, plan.policy)

			snapshot_or_blob = yield from self.__load_or_cut_chunks(actual_path_to_read, plan.pre_cal_result, src_path_str)
			if isinstance(snapshot_or_blob, schema.Blob):
				return snapshot_or_blob
			snapshot: _ChunkedBlobSnapshot = snapshot_or_blob
			if snapshot.blob_size == 0:
				self.log_and_raise_blob_file_changed('Blob size becomes zero', self.args.last_chance)

			# notes: the following code cannot be interrupted (yield).
			# The blob is specifically generated by the generator
			# if any yield is done, ensure to check blob_by_hash_cache again
			process_start_time = time.time()

			# large files that need to be chunked already contain quite a few chunks,
			# so it's efficient enough to directly query for chunks from DB here
			with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_db):
				known_db_chunks = self.ctx.session.get_chunks_by_hashes_opt(list(snapshot.chunks.iter_hashes()))

			write_result = self.__create_missing_chunks(actual_path_to_read, snapshot, known_db_chunks)

		if self.logger.isEnabledFor(logging.DEBUG):
			self.logger.debug('Chunked file {} in {:.2f}s, compressed size {}/{}, chunk count: {} (+{}, {:.1f}%)'.format(
				src_path_str, time.time() - process_start_time,
				write_result.stored_size_sum, write_result.raw_size_sum,
				len(write_result.offset_to_chunk), len(write_result.new_chunks),
				100.0 * len(write_result.new_chunks) / max(1, len(write_result.offset_to_chunk)),
			))
		if (
				len(write_result.new_chunks) >= max(5000, int(write_result.unique_chunk_count * 0.6)) and
				self.ctx.file_lookup.previous_backup_has_chunked_file(self.args.src_path)
		):
			# 5000 chunks == 5000*32*1.2 == ~192MiB
			self.logger.warning('Chunked a large file with lots of new chunks, please consider if it should really be in the chunking target patterns')
			self.logger.warning('File path: {} size {}, chunk method {}, chunk count {} (unique {}, new {} {:.1f}%), new chunk size {}'.format(
				src_path_str, ByteCount(write_result.raw_size_sum).auto_str(),
				self.args.chunk_method.name, len(snapshot.chunks), write_result.unique_chunk_count,
				len(write_result.new_chunks), 100.0 * len(write_result.new_chunks) / max(1, write_result.unique_chunk_count),
				ByteCount(sum(db_chunk.raw_size for db_chunk in write_result.new_chunks)).auto_str(),
			))

		return self.__create_chunked_blob(snapshot, write_result)

	def __select_plan(self) -> _ChunkedBlobPlan:
		pre_cal_result: Optional[BlobPrecalculateResult] = None
		if self.args.last_chance or self.args.is_mutating_file:
			policy = _ChunkedBlobCreatePolicy.copy_hash
		else:
			policy = _ChunkedBlobCreatePolicy.default
			pre_cal_result = self.ctx.file_lookup.pop_pre_calc_result(self.args.src_path)
		if pre_cal_result is not None and (self.args.st.st_size != pre_cal_result.size or pre_cal_result.should_be_chunked is False):
			if self.logger.isEnabledFor(logging.DEBUG):
				self.logger.debug('Drop pre cal result for path {} due to stat mismatched, st.st_size {}, pre_cal_result {}'.format(
					self.args.src_path, self.args.st.st_size, pre_cal_result.simple_repr(),
				))
			pre_cal_result = None
		return _ChunkedBlobPlan(policy, pre_cal_result)

	def __prepare_path_to_read(self, es: contextlib.ExitStack, policy: _ChunkedBlobCreatePolicy) -> Path:
		if policy == _ChunkedBlobCreatePolicy.default:
			return self.args.src_path
		if policy == _ChunkedBlobCreatePolicy.copy_hash:
			# copy to temp file, then do whatever processing
			temp_file_path = es.enter_context(self.ctx.make_temp_file(self.args.src_path_md5))
			with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_io_copy), SourceFileNotFoundWrapper.wrap(self.args.src_path):
				# copy as fast as possible, no bypass tricks, since it's a volatile file
				file_utils.copy_file_fast(self.args.src_path, temp_file_path)
			return temp_file_path
		raise AssertionError('bad policy {!r}'.format(policy))

	def __load_or_cut_chunks(self, actual_path_to_read: Path, pre_cal_result: Optional[BlobPrecalculateResult], src_path_str: str) -> BlobLookupRoutine[Union[_ChunkedBlobSnapshot, schema.Blob]]:
		pre_calc_blob_hash: Optional[str] = None
		if pre_cal_result is not None:
			pre_calc_blob_hash = pre_cal_result.hash
			if pre_cal_result.chunks is not None:
				chunks = pre_cal_result.chunks
				blob_size = pre_cal_result.size
				if self.logger.isEnabledFor(logging.DEBUG):
					self.logger.debug('Cut and hashed file {} with size {} into {} chunks using {} (precalc)'.format(
						src_path_str, ByteCount(blob_size).auto_str(), len(chunks), self.args.chunk_method.name,
					))
				if (cache := (yield from self.query_cached_blob(pre_calc_blob_hash))) is not None:
					if self.logger.isEnabledFor(logging.DEBUG):
						self.logger.debug('Chunked file {} (hash {}) already exists in DB'.format(src_path_str, pre_calc_blob_hash))
					return cache
				return _ChunkedBlobSnapshot(chunks, pre_calc_blob_hash, blob_size)

		if pre_calc_blob_hash is not None:
			if (cache := (yield from self.query_cached_blob(pre_calc_blob_hash))) is not None:
				if self.logger.isEnabledFor(logging.DEBUG):
					self.logger.debug('Chunked file {} (hash {}) already exists in DB'.format(src_path_str, pre_calc_blob_hash))
				return cache

		if (
				pre_calc_blob_hash is None and
				not self.args.last_chance and
				not self.args.is_mutating_file and
				self.ctx.file_lookup.is_stat_unchanged_file(self.args.src_path)
		):
			with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_io_read) as hash_cost:
				with SourceFileNotFoundWrapper.wrap(actual_path_to_read):
					sah = hash_utils.calc_file_size_and_hash(actual_path_to_read)
			if sah.size != self.args.st.st_size:
				self.log_and_raise_blob_file_changed('Blob size mismatch, previous: {}, current: {}'.format(self.args.st.st_size, sah.size), self.args.last_chance)
			pre_calc_blob_hash = sah.hash
			if self.logger.isEnabledFor(logging.DEBUG):
				self.logger.debug('Hashed stat unchanged chunked file {} with size {} in {:.2f}s ({}/s)'.format(
					src_path_str, ByteCount(sah.size).auto_str(), hash_cost(),
					ByteCount(sah.size / hash_cost() if hash_cost() > 0 else 0).auto_str(),
				))
			if (cache := (yield from self.query_cached_blob(pre_calc_blob_hash))) is not None:
				if self.logger.isEnabledFor(logging.DEBUG):
					self.logger.debug('Chunked file {} (hash {}) already exists in DB'.format(src_path_str, pre_calc_blob_hash))
				return cache

		previous_chunks = self.ctx.file_lookup.get_previous_chunks(self.args.src_path) if self.args.chunk_method.needs_previous_chunks() else None
		chunker = self.args.chunk_method.create_file_chunker(actual_path_to_read, need_entire_file_hash=True, previous_chunks=previous_chunks)
		with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_io_read) as chunking_cost:
			chunks = SimplePrettyChunkSequence(chunker.cut_all())
		blob_hash = chunker.get_entire_file_hash()
		blob_size = chunker.get_read_file_size()
		if pre_calc_blob_hash is not None and pre_calc_blob_hash != blob_hash:
			self.log_and_raise_blob_file_changed('Blob hash mismatch, pre calc {}, chunked {}'.format(pre_calc_blob_hash, blob_hash), self.args.last_chance)

		if self.logger.isEnabledFor(logging.DEBUG):
			self.logger.debug('Cut and hashed file {} with size {} into {} chunks using {} in {:.2f}s ({}/s)'.format(
				src_path_str, ByteCount(blob_size).auto_str(), len(chunks), self.args.chunk_method.name, chunking_cost(),
				ByteCount(blob_size / chunking_cost() if chunking_cost() > 0 else 0).auto_str(),
			))
		if pre_calc_blob_hash is None and (cache := (yield from self.query_cached_blob(blob_hash))) is not None:
			if self.logger.isEnabledFor(logging.DEBUG):
				self.logger.debug('Chunked file {} (hash {}) already exists in DB'.format(src_path_str, blob_hash))
			return cache
		return _ChunkedBlobSnapshot(chunks, blob_hash, blob_size)

	def __create_missing_chunks(self, actual_path_to_read: Path, snapshot: _ChunkedBlobSnapshot, known_db_chunks: Dict[str, Optional[schema.Chunk]]) -> _ChunkWriteResult:
		known_chunks: Dict[str, Optional[Union[schema.Chunk, _PendingChunk]]] = dict(known_db_chunks)
		new_chunks: List[_PendingChunk] = []
		offset_to_chunk: Dict[int, Union[schema.Chunk, _PendingChunk]] = {}
		write_state = _CompressedChunkWriteState()

		with contextlib.ExitStack() as es:
			src_file = es.enter_context(open(actual_path_to_read, 'rb'))
			pool: Optional[FailFastBlockingThreadPool] = None
			if self.config.get_effective_concurrency() > 1:
				pool = es.enter_context(FailFastBlockingThreadPool('chunk_compress'))

			offset = 0
			for chunk in snapshot.chunks:
				misc_utils.assert_true(offset == chunk.offset, lambda: f'offset mismatch {offset} {chunk.offset}')
				misc_utils.assert_true(chunk.length > 0, lambda: 'chunk with zero length')

				db_chunk = known_chunks[chunk.hash]
				if db_chunk is None:
					db_chunk = self.__create_new_chunk(src_file, chunk, offset, known_chunks, new_chunks, pool, write_state)
				else:
					self.__skip_known_chunk(src_file, chunk, offset)

				offset_to_chunk[offset] = db_chunk
				offset += chunk.length

			extra_buf = src_file.read(1)
			if len(extra_buf) > 0:
				self.log_and_raise_blob_file_changed('Blob size mismatch, actual size larger than expected size {}'.format(snapshot.blob_size), self.args.last_chance)

			with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_io_write):
				if pool is not None:
					pool.wait_and_ensure_no_error()
				self.__flush_compressed_chunk_futures(write_state, force=True)

		blob_raw_size_sum = 0
		blob_stored_size_sum = sum({db_chunk.hash: db_chunk.stored_size for db_chunk in offset_to_chunk.values()}.values())
		for db_chunk in offset_to_chunk.values():
			blob_raw_size_sum += db_chunk.raw_size
		misc_utils.assert_true(blob_raw_size_sum == offset, lambda: f'blob_raw_size_sum {blob_raw_size_sum} should be equal to offset {offset}')
		misc_utils.assert_true(blob_raw_size_sum == snapshot.blob_size, lambda: f'blob_raw_size_sum {blob_raw_size_sum} should be equal to blob_size {snapshot.blob_size}')

		return _ChunkWriteResult(
			offset_to_chunk=offset_to_chunk,
			new_chunks=new_chunks,
			raw_size_sum=blob_raw_size_sum,
			stored_size_sum=blob_stored_size_sum,
			unique_chunk_count=len(known_db_chunks),
		)

	def __create_new_chunk(
			self,
			src_file: BinaryIO,
			chunk: PrettyChunk,
			offset: int,
			known_chunks: Dict[str, Optional[Union[schema.Chunk, _PendingChunk]]],
			new_chunks: List[_PendingChunk],
			pool: Optional[FailFastBlockingThreadPool],
			write_state: _CompressedChunkWriteState,
	) -> _PendingChunk:
		chunk_buf = self.__read_and_validate_new_chunk(src_file, chunk, offset)
		compress_method: CompressMethod = self.config.backup.get_compress_method_from_size(chunk.length)
		compressor = Compressor.create(compress_method)

		db_chunk = _PendingChunk(
			hash=chunk.hash,
			compress=compress_method.name,
			raw_size=len(chunk_buf),
			stored_size=-1,
			pack_id=-1,
			pack_offset=-1,
		)
		new_chunks.append(db_chunk)
		known_chunks[db_chunk.hash] = db_chunk

		with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_io_write):
			def write_task(db_chunk_: _PendingChunk = db_chunk, compressor_: Compressor = compressor, chunk_buf_: bytes = chunk_buf) -> _CompressedChunk:
				compressed = compressor_.compress_bytes(chunk_buf_)
				return _CompressedChunk(db_chunk_, compressed)

			if pool is not None:
				write_state.futures.append(pool.submit(write_task))
			else:
				fut: 'Future[_CompressedChunk]' = Future()
				fut.set_result(write_task())
				write_state.futures.append(fut)
			write_state.pending_bytes += db_chunk.raw_size

			self.__flush_compressed_chunk_futures(write_state, force=False)
		return db_chunk

	def __read_and_validate_new_chunk(self, src_file: BinaryIO, chunk: PrettyChunk, offset: int) -> bytes:
		with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_io_read):
			chunk_buf = src_file.read(chunk.length)
		if len(chunk_buf) != chunk.length:
			self.log_and_raise_blob_file_changed('Blob size mismatch, fail to read {} byte at offset {}, actual read {}'.format(chunk.length, offset, len(chunk_buf)), self.args.last_chance)
		new_chunk_hash = chunk_utils.calc_bytes_hash(chunk_buf)
		if new_chunk_hash != chunk.hash:
			self.log_and_raise_blob_file_changed('Blob content mismatch, chunk at [{}, {}) has its hash changed, previous {}, current {}'.format(offset, offset + chunk.length, chunk.hash, new_chunk_hash), self.args.last_chance)
		return chunk_buf

	def __flush_compressed_chunk_futures(self, write_state: _CompressedChunkWriteState, force: bool):
		while write_state.should_flush(force):
			compressed_chunk = write_state.futures.pop(0).result()
			write_state.pending_bytes -= compressed_chunk.chunk.raw_size
			entry_location = self.ctx.pack_writer.write_entry(compressed_chunk.data)
			compressed_chunk.chunk.stored_size = len(compressed_chunk.data)
			compressed_chunk.chunk.pack_id = entry_location.pack_id
			compressed_chunk.chunk.pack_offset = entry_location.offset

	def __skip_known_chunk(self, src_file: BinaryIO, chunk: PrettyChunk, offset: int):
		if src_file.seekable():
			new_offset = src_file.seek(offset + chunk.length)
			if new_offset != offset + chunk.length:
				self.log_and_raise_blob_file_changed('Blob size mismatch, fail to seek to offset {}, actual seek {}'.format(offset + chunk.length, new_offset), self.args.last_chance)
		else:
			n_read = len(src_file.read(chunk.length))
			if n_read != chunk.length:
				self.log_and_raise_blob_file_changed('Blob size mismatch, fail to read {} byte at offset {}, actual read {}'.format(chunk.length, offset, n_read), self.args.last_chance)

	def __create_chunked_blob(self, snapshot: _ChunkedBlobSnapshot, write_result: _ChunkWriteResult) -> schema.Blob:
		for new_chunk in write_result.new_chunks:
			misc_utils.assert_true(new_chunk.stored_size >= 0, lambda: f'bad stored_size {new_chunk}')
			self.ctx.blob_recorder.record_new_chunk_size(new_chunk.raw_size, new_chunk.stored_size)

		with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_db):
			new_chunk_ids = self.ctx.session.insert_chunks([new_chunk.to_insert_kwargs() for new_chunk in write_result.new_chunks])

		offset_to_chunk_like: Dict[int, ChunkGrouper.ChunkLike] = {}
		for offset, chunk in write_result.offset_to_chunk.items():
			if isinstance(chunk, _PendingChunk):
				offset_to_chunk_like[offset] = chunk.to_chunk_like(new_chunk_ids[chunk.hash])
			else:
				offset_to_chunk_like[offset] = ChunkGrouper.ChunkLike.of(chunk)

		blob = self.ctx.blob_recorder.create_blob(
			self.ctx.session,
			storage_method=BlobStorageMethod.chunked.value,
			hash=snapshot.blob_hash,
			compress=CompressMethod.plain.name,
			raw_size=write_result.raw_size_sum,
			stored_size=write_result.stored_size_sum,
		)
		with self.ctx.time_costs.measure_time_cost(CreateBackupTimeCostKey.kind_db):
			self.ctx.session.flush()  # creates blob.id

		grouper = ChunkGrouper(self.ctx.session, self.ctx.time_costs)
		grouper.create_chunk_groups(blob, offset_to_chunk_like)
		return blob
